# Generated by Django 5.2.3 on 2025-06-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка на подозрительный контент')),
                ('reported_by', models.CharField(blank=True, max_length=255, verbose_name='Отправитель жалобы')),
                ('description', models.TextField(verbose_name='Описание жалобы')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Обработано?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
            ],
        ),
    ]
