# Generated by Django 5.2.3 on 2025-06-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(default='other', max_length=100, verbose_name='Категория жалобы'),
        ),
    ]
